/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        gold: {
          DEFAULT: '#C9A961',
          light: '#D4BA7F',
          dark: '#B89950',
        },
        beige: {
          DEFAULT: '#F5F1E8',
          light: '#FAF8F2',
          dark: '#EDE7D9',
        },
        slate: {
          DEFAULT: '#4A5F6D',
          light: '#5A7080',
          dark: '#3A4F5D',
        },
        textGray: '#626670',
        "on-primary-container": "#554300",
        "tertiary": "#415ba4",
        "inverse-primary": "#e9c349",
        "inverse-surface": "#2f3133",
        "on-primary-fixed": "#241a00",
        "secondary": "#5f5e5e",
        "surface": "#f9f9fc",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-fixed-variant": "#574500",
        "on-secondary-container": "#656464",
        "primary-fixed-dim": "#e9c349",
        "surface-variant": "#e2e2e5",
        "surface-bright": "#f9f9fc",
        "surface-container-high": "#e8e8ea",
        "on-surface-variant": "#4d4635",
        "surface-dim": "#dadadc",
        "on-tertiary-fixed-variant": "#27438a",
        "background": "#f9f9fc",
        "outline": "#7f7663",
        "outline-variant": "#d0c5af",
        "on-background": "#1a1c1e",
        "on-secondary-fixed-variant": "#474747",
        "secondary-fixed": "#e4e2e1",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f3f6",
        "tertiary-fixed-dim": "#b4c5ff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e2e2e5",
        "on-error-container": "#93000a",
        "surface-container": "#eeeef0",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-container": "#254188",
        "on-surface": "#1a1c1e",
        "secondary-container": "#e4e2e1",
        "primary-container": "#d4af37",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#00174b",
        "primary-fixed": "#ffe088",
        "inverse-on-surface": "#f0f0f3",
        "primary": "#735c00",
        "tertiary-fixed": "#dbe1ff",
        "surface-tint": "#735c00",
        "tertiary-container": "#97b0ff"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'admin-ambient': '0 12px 40px -5px rgba(0, 0, 0, 0.06)',
      }
    },
  },
  plugins: [],
}
